#!/usr/bin/env python3
"""Generate bounded BUS M0 preload metadata from the one Host contract."""
import argparse
import hashlib
import json
from pathlib import Path

from generate_host_proposal import generate, layout, number


def files(contract_bytes):
    contract = json.loads(contract_bytes)
    x = layout(contract)
    content = generate(contract, number(contract["host_proposal"]["m0_entry"]))
    original = content["amp.its"]
    marker = "        rockchip,mcu-shared-window-base"
    additions = (
        f"        rockchip,mcu-code-size = <0x{x['code_size']:x}>;\n"
        f"        rockchip,mcu-shared-region = <0x{x['shared_pa']:x} 0x{x['shared_size']:x}>;\n"
    )
    assert original.count(marker) == 1
    content["amp.its"] = original.replace(marker, additions + marker).replace(
        '    description = "HOST PROPOSAL - cold BUS M0";',
        '    description = "HOST PROPOSAL - cold BUS M0";\n'
        '    totalsize = <0>; /* Finalized before signing; pinned loader property. */'
    )
    content["amp_project_contract.h"] = content["amp_contract.h"].replace(
        "AMP_CONTRACT_H", "AMP_PROJECT_CONTRACT_H"
    ).replace(
        "/* Generated Host proposal. No deployment authorization. */",
        "/* Generated by p026_generate_preload_contract.py; Host only.\n"
        f" * Contract SHA256: {hashlib.sha256(contract_bytes).hexdigest()}\n */"
    ).replace(
        "#define AMP_COLD_START_UNCACHED 1",
        "#define AMP_COLD_START_UNCACHED 1\n"
        f"#define AMP_M0_LOCAL_ENTRY 0x{number(contract['host_proposal']['m0_entry']):08x}\n"
        "#define AMP_PRELOAD_PROJECT_BUS_M0_ONLY 1\n"
        "#define AMP_PROJECT_EXPLICIT_FILE_ONLY 1"
    )
    return content


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--contract", type=Path, required=True)
    p.add_argument("--output", type=Path, required=True)
    p.add_argument("--uboot-source", type=Path)
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    generated = files(a.contract.read_bytes())
    if a.check:
        for name, value in generated.items():
            assert (a.output / name).read_text() == value, f"stale generated {name}"
        if a.uboot_source:
            assert (a.uboot_source / "include/amp_project_contract.h").read_text() == generated["amp_project_contract.h"]
        print("P026_CONTRACT_INPUTS_MATCH; no deployment authorization")
    else:
        a.output.mkdir(parents=True, exist_ok=False)
        for name, value in generated.items():
            (a.output / name).write_text(value)
        if a.uboot_source:
            (a.uboot_source / "include/amp_project_contract.h").write_text(generated["amp_project_contract.h"])
        print("P026_HOST_INPUTS_GENERATED; no board access")


if __name__ == "__main__":
    main()
