#!/usr/bin/env python3
"""Build a traceable P026 candidate changeset; never grant deployment or board D."""
import argparse
import json
from pathlib import Path
import subprocess

from make_deployment_packet import ROOT, REVIEW, record, sha


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--uboot-source', type=Path, required=True)
    ap.add_argument('--uboot-build', type=Path, required=True)
    ap.add_argument('--uboot-package', type=Path, required=True)
    args = ap.parse_args()
    for name in ('uboot_source', 'uboot_build', 'uboot_package'):
        value = getattr(args, name)
        setattr(args, name, (ROOT / value).resolve())
    prior = json.loads((REVIEW / 'P025_ARTIFACT_MANIFEST.json').read_text())
    contract = json.loads((ROOT / prior['contract']['file']).read_text())
    board = json.loads((REVIEW / 'P026_BOARD_READ_EVIDENCE.json').read_text())
    kernel = ROOT / 'artifacts/local/p026-kernel-isolated-clean'
    release = (kernel / 'include/config/kernel.release').read_text().strip()
    assert release == '6.1.99-rk3576-m0echo-p026'
    paired = json.loads((kernel / 'result.json').read_text())
    assert paired['status'] == 'HOST_PAIRED_BUILD_PASS' and paired['build_warning_count'] == 0
    assert json.loads((kernel / 'initrd-result.json').read_text())['status'] == 'HOST_PAIRED_INITRD_PASS'
    source = subprocess.check_output(['git', '-C', str(args.uboot_source), 'rev-parse', 'HEAD'], text=True).strip()
    assert not subprocess.check_output(['git', '-C', str(args.uboot_source), 'status', '--porcelain'], text=True).strip()
    version = (args.uboot_build / 'include/generated/version_autogenerated.h').read_text()
    assert '-g' + source[:7] in version and '-dirty' not in version
    package_result = json.loads((args.uboot_package / 'result.json').read_text())
    assert package_result['exit_code'] == 0 and package_result['copies'] == 2
    assert package_result['package_size'] == 4194304
    assert package_result['package_sha256'] == record(args.uboot_package / 'uboot-host-unsigned.img')['sha256']
    ub_payload = next(p for p in package_result['preserved_payloads'] if p['name'] == 'uboot')
    assert ub_payload['sha256'] == record(args.uboot_build / 'u-boot-nodtb.bin')['sha256']
    assert all(p['unchanged_from_recovery'] for p in package_result['preserved_payloads'] if p['name'] != 'uboot')
    fit_result = json.loads((ROOT / 'artifacts/local/p026-fit-clean-v2/result.json').read_text())
    assert fit_result['exit_code'] == 0 and fit_result['external_payload_identical']
    assert fit_result['contract_sha256'] == record(prior['contract']['file'])['sha256']
    assert fit_result['payload_sha256'] == record(fit_result['payload_source'])['sha256']
    board_flag = board['verified_boot_read']
    assert board_flag['open_result'] == board_flag['invoke_result'] == 0
    assert board_flag['bytes'] == 4 and board_flag['vendor_required_flag'] == 0
    assert board_flag['proper_uboot_actual_call_observed'] is False
    artifacts = []
    # Reuse only explicitly identified M0/DT source outputs; supersede old FIT/kernel/U-Boot.
    for item in prior['artifacts']:
        path = item['file']
        if 'p023-m0-clean-v5/' in path or path.endswith(('amp-host.dtb', 'amp-host.dtbo', 'rttmcu.bin')):
            actual = record(path)
            assert actual['sha256'] == item['sha256']
            artifacts.append({**item, 'rechecked_milestone': 'P026'})

    def add(path, purpose, architecture, commit, command):
        artifacts.append(record(path, purpose=purpose, architecture=architecture, source_commit=commit,
                                build_command=command, deployment_authorized=False, built_milestone='P026'))

    for name in ('u-boot', 'u-boot.bin', 'u-boot-nodtb.bin', 'u-boot.dtb'):
        add(args.uboot_build / name, 'explicit file-only BUS M0 candidate, original control DT retained',
            'FDT' if name.endswith('.dtb') else 'AArch64', source, 'build_uboot_fit_policy_host.sh SOURCE NEW_OUTPUT enabled')
    for name in ('loader-host.itb', 'uboot-host-unsigned.img'):
        add(args.uboot_package / name, 'Host package; original BL31/OP-TEE/FDT; no current board execution',
            'FIT/AArch64', source, 'package_uboot_host_fit.py --original ORIGINAL --build BUILD --output NEW')
    add('artifacts/local/p026-fit-clean-v2/amp-host.itb', 'single BUS M0 image plus checked full reservation metadata',
        'FIT/ARMv6-M', prior['sources']['rtos']['commit'], 'p026_build_fit.py --contract CONTRACT --bin BIN --output NEW')
    artifacts[-1].update(loader_source_commit=source, payload_sha256=fit_result['payload_sha256'],
                         payload_source=fit_result['payload_source'], metadata_source='canonical host_proposal')
    for relative, purpose, arch in (
            ('arch/arm64/boot/Image', 'paired known-source Linux candidate', 'AArch64'),
            ('echo/rk3576_amp_echo_test.ko', 'manual HELLO/PING, no autoload', 'AArch64 ELF REL'),
            ('modules-' + release + '.tar', '255 paired modules; isolated new release directory', 'AArch64 modules tar'),
            ('initrd.img-' + release, 'Debian original initrd with paired module/metadata', 'gzip/newc'),
            ('System.map', 'paired kernel symbol map', 'text'), ('.config', 'generated kernel config', 'text')):
        add(kernel / relative, purpose, arch, paired['source_commit'], 'p026_build_isolated_kernel.sh; p026_finalize_kernel.py; p026_pair_initrd.py')
    baseline = prior['baseline']
    baseline['raw_uboot'] = board['original_firmware']['raw']
    baseline['installed_modules_backup'] = record('artifacts/local/p026-board-modules-20261002T185242Z-1007865/modules.tar')
    baseline['evidence_files'] += [baseline['raw_uboot'], baseline['installed_modules_backup'],
                                  record('docs/reviews/rk3576-amp-platform-closure/P026_BOARD_READ_EVIDENCE.json')]
    sources = prior['sources']
    sources['uboot']['parent'] = '96c9a009eed997c318cd247943e5fc88e8e1bcc6'
    sources['uboot']['commit'] = source
    sources['uboot']['patch'] = '0008-uboot-preload-and-explicit-fit-file.patch'
    manifest = {'schema_version': 1, 'date': '2026-10-03', 'amp_grade': 'C. HOST_BUILD_PASS',
                'status': 'HOST_REVIEWED_BOARD_RUNTIME_BLOCKED', 'contract': record(prior['contract']['file']),
                'sources': sources, 'artifacts': artifacts, 'baseline': baseline,
                'recovery_image': prior['recovery_image'], 'recovery_image_sha256': prior['recovery_image_sha256'],
                'whole_board_recovery': prior['whole_board_recovery'],
                'evidence': [record(p) for p in (
                    args.uboot_build / '.config', args.uboot_build / 'build.log', args.uboot_package / 'result.json',
                    args.uboot_build / 'include/generated/version_autogenerated.h',
                    args.uboot_source / 'include/amp_project_contract.h',
                    'artifacts/local/p026-fit-clean-v2/result.json',
                    kernel / 'result.json', kernel / 'initrd-result.json',
                    kernel / 'Module.symvers', kernel / 'hashes.sha256',
                    'artifacts/local/p026-primary-reviewed-preload/result.json',
                    'artifacts/local/p026-primary-reviewed-policy/result.json',
                    'artifacts/local/p026-board-module-audit/result.json',
                    'artifacts/local/p026-partition-sector-observation.txt',
                    'artifacts/local/p026-desktop-originals.json',
                    'artifacts/local/p024-recovery-image/payloads/bootloader.payload',
                    'artifacts/local/p024-recovery-image/payloads/parameter.txt',
                    'artifacts/local/p026-rkdevtool-manual.pdf',
                    'patches/rk3576-amp-platform/0008-uboot-preload-and-explicit-fit-file.patch')]}
    by_file = {a['file']: a for a in artifacts}

    def new_file(path, destination, purpose):
        path = str(Path(path).relative_to(ROOT)) if Path(path).is_absolute() else str(path)
        return {'kind': 'new_file', 'source': path, 'destination': destination,
                'old': 'ABSENT_RECHECK_BEFORE_WRITE', 'new_sha256': by_file[path]['sha256'],
                'purpose': purpose, 'rollback': 'restore original links first; remove only task-created path',
                'deployment_authorized': False}

    def link(name, target):
        return {'kind': 'symlink', 'destination': '/boot/' + name, 'old': baseline['files'][name],
                'new': {'type': 'symlink', 'target': target, 'sha256_link_text': sha(target.encode())},
                'rollback': 'restore old target after original SHA check', 'deployment_authorized': False}

    changes = [
        new_file(kernel / 'arch/arm64/boot/Image', '/boot/Image-' + release, 'isolated paired Linux release'),
        new_file(kernel / ('initrd.img-' + release), '/boot/initrd.img-' + release, 'paired initrd'),
        new_file('artifacts/local/p023-dt-fit-clean-v3/amp-host.dtb',
                 '/boot/dtb/rk3576-lubancat-3-v2-m0echo-p026.dtb', 'no-map MCU/rings/pool; other board resources preserved'),
        new_file('artifacts/local/p026-fit-clean-v2/amp-host.itb', '/boot/amp/amp.itb', 'passive file; no automatic M0 start'),
        new_file(kernel / ('modules-' + release + '.tar'), '/lib/modules/' + release,
                 'extract only release subtree from archive; never replace stock module directory'),
        new_file(kernel / 'echo/rk3576_amp_echo_test.ko', '/opt/rk3576-amp-test/rk3576_amp_echo_test.ko', 'manual echo only'),
        link('Image', 'Image-' + release), link('initrd', 'initrd.img-' + release),
        link('rk-kernel.dtb', 'dtb/rk3576-lubancat-3-v2-m0echo-p026.dtb'),
        {'kind': 'firmware_partition', 'source': str((args.uboot_package / 'uboot-host-unsigned.img').relative_to(ROOT)),
         'destination': '/dev/disk/by-partlabel/uboot (observed mmcblk0p1, start sector 0x4000)',
         'old_sha256': board['original_firmware']['raw']['sha256'],
         'old_prefix_4MiB_sha256': board['original_firmware']['first4MiB_sha256'],
         'write_length': 4194304, 'partition_length': 8388608,
         'new_sha256': by_file[str((args.uboot_package / 'uboot-host-unsigned.img').relative_to(ROOT))]['sha256'],
         'purpose': 'new explicit-only command; no power-on M0 auto start; retains old firmware',
         'risk': 'bootloader replacement requires separate L3 approval; no current execution evidence',
         'rollback': 'restore exact original 8MiB; otherwise user-tested official MR full recovery',
         'deployment_authorized': False}]
    packet = {'schema_version': 1, 'status': 'BLOCKED', 'deployment_authorized': False,
              'manifest': 'P026_ARTIFACT_MANIFEST.json', 'contract': manifest['contract'],
              'proposal': contract['host_proposal'], 'changes': changes,
              'partition_changes': 'NONE; rootfs/GPT untouched in project file-only plan',
              'untouched_originals': ['uEnv/uEnv.txt', 'boot.cmd', 'boot.scr', 'Image-6.1.99-rk3576',
                  'initrd.img-6.1.99-rk3576', 'dtb/rk3576-lubancat-3-v2.dtb', '/lib/modules/6.1.99-rk3576'],
              'gates': {'runtime_sip_mapping_and_cache': 'BLOCKED',
                  'vendor_tee_verified_boot_flag_read': 'PASS',
                  'proper_uboot_verification_policy_host': 'PASS',
                  'fit_load_source_and_no_gpt_change_host': 'PASS',
                  'full_code_shared_preload_reservation': 'PASS',
                  'candidate_kernel_module_paired_identity_host': 'PASS',
                  'uart5_runtime_ownership_and_signal_plan': 'PASS',
                  'current_raw_uboot_prewrite_identity': 'PASS', 'whole_board_recovery_user_test': 'PASS',
                  'current_or_replaced_uboot_actual_amp_capability': 'BLOCKED'},
              'first_test_scope': ['Linux boot', 'M0 banner', 'HELLO/HELLO_ACK', 'PING/PONG'],
              'future_explicit_command': 'amp_m0load /amp/amp.itb 0x48300000 (only after exact AMP Linux FDT load)',
              'verification_evidence': {
                  'board_observation': 'Linux vendor OP-TEE command5 returned 4-byte zero',
                  'proper_uboot_same_abi_interpretation': 'SOURCE_INFERRED required=0; runtime failures remain required=1',
                  'global_secure_boot_or_otp_disabled': 'NOT_PROVED',
                  'proper_uboot_amp_call_observed': False},
              'reboot_required_for_future_boot_chain_change': True,
              'approval_gate_board_test': 'CLOSED'}
    for name, value in (('P026_ARTIFACT_MANIFEST.json', manifest), ('P026_DEPLOYMENT_CHANGESET.json', packet)):
        (REVIEW / name).write_text(json.dumps(value, indent=2, ensure_ascii=False) + '\n')
    (REVIEW / 'AMP_ARTIFACT_MANIFEST.json').write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + '\n')
    print('P026_HOST_PACKET_COMPLETE; D and deployment remain BLOCKED')


if __name__ == '__main__':
    main()
