#!/usr/bin/env python3
"""Record Host candidate hashes and explicit missing deployable AMP artifacts."""
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'docs/reviews/rk3576-amp-platform-closure/AMP_ARTIFACT_MANIFEST.json'
BASE = ROOT / 'artifacts/local/amp-platform-candidate-build'
KO = ROOT / 'artifacts/local/amp-linux-echo-final/rk3576_amp_echo_test.ko'
RTOS_COMMIT = '1d0de06c394f89be35a4b6966e766b56f035c19d'
HAL_COMMIT = '277de3fd4b0e640654ee73bb3308be2ef01e3aad'


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def record(path, architecture, purpose, command, source_commit, status):
    if not path.is_file():
        raise FileNotFoundError(path)
    return {'file': str(path.relative_to(ROOT)), 'sha256': sha(path),
            'bytes': path.stat().st_size, 'source_commit': source_commit,
            'architecture': architecture, 'purpose': purpose,
            'build_command': command, 'status': status}


def main():
    project_commit = subprocess.check_output(['git', '-C', str(ROOT), 'rev-parse', 'HEAD'], text=True).strip()
    candidate = 'bash scripts/amp/build_candidate_host.sh'
    module = 'bash scripts/amp/build_linux_echo_against_board_headers.sh'
    result = {
        'schema_version': 1,
        'release_status': 'BLOCKED_PREBOARD',
        'note': 'Host candidates only. No file in this manifest is approved for board deployment.',
        'fixed_reference_commits': {
            'rk3576-rtos': '7c397f41751feb29b0b388dfda3d2c2225f1f87c',
            'rk3576-hal': HAL_COMMIT},
        'artifacts': [
            record(BASE / 'rtthread.elf', 'ARMv6-M ELF32 EABI5 soft-float', 'M0 debug/link audit', candidate, RTOS_COMMIT, 'HOST_CANDIDATE_ONLY'),
            record(BASE / 'rtthread.map', 'ARMv6-M link map', 'M0 section/address audit', candidate, RTOS_COMMIT, 'HOST_CANDIDATE_ONLY'),
            record(BASE / 'rtthread.bin', 'ARMv6-M raw binary', 'FIT payload sample', candidate, RTOS_COMMIT, 'HOST_CANDIDATE_ONLY'),
            record(BASE / 'fit/amp.img', 'ARM FIT', 'Unsigned structurally valid sample with conflicting 0x47800000 load', candidate, RTOS_COMMIT, 'HOST_CANDIDATE_ONLY'),
            record(KO, 'AArch64 ELF64 relocatable', 'Linux RPMsg service matching Host module', module, project_commit, 'HOST_CANDIDATE_ONLY'),
        ],
        'unavailable_release_artifacts': [
            {'file': 'rttmcu.bin', 'sha256': None, 'reason': 'not generated by candidate SCons/FIT path'},
            {'file': 'signed final amp.itb', 'sha256': None, 'reason': 'final load/source/signing policy unresolved'},
            {'file': 'rk3576-lubancat-3-v2-amp.dtb/dtbo', 'sha256': None, 'reason': 'final PA/CON17/cache/DTS unresolved'},
            {'file': 'board-ready rk3576_amp_echo_test.ko', 'sha256': None, 'reason': 'exact kernel source commit and board transport not closed'},
        ],
    }
    OUT.write_text(json.dumps(result, indent=2, ensure_ascii=False) + '\n')
    print(OUT)


if __name__ == '__main__':
    main()
