# Template only; not a validated vendor SDK/toolchain configuration.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
find_program(COCKPIT_CXX aarch64-linux-gnu-g++ REQUIRED)
set(CMAKE_CXX_COMPILER "${COCKPIT_CXX}")
set(COCKPIT_TARGET_SYSROOT "" CACHE PATH "Verified target sysroot; required before target integration")
if(NOT IS_DIRECTORY "${COCKPIT_TARGET_SYSROOT}")
  message(FATAL_ERROR "Provide -DCOCKPIT_TARGET_SYSROOT=/absolute/path/to/verified/sysroot")
endif()
set(CMAKE_SYSROOT "${COCKPIT_TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${COCKPIT_TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
